Belizzi/urls.py
from django.contrib import admin
from django.urls import path, include
from pages.views import homepage
from Category.views import  menu_view

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', homepage, name='home'),
    path('home/', homepage, name='home'),
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('menu/', menu_view, name='menu'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

orders/urls.py
  
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    url(r'^all/$', views.all_orders, name='all_orders')
    
]

Category/models.py
from django.db import models
from itertools import chain
from enum import Enum


Categoies_enum = (
    ("Burger", "Burger"),
    ("Pizza", "Pizza"),
    ("Drink", "Drink"),
    ("Dessert", "Dessert"))

    
class Product(models.Model):
    name = models.CharField(default='Product name', max_length=100)
    category = models.CharField(max_length=100, choices=Categoies_enum)
    preparing_time = models.CharField(default='10-15min', max_length=1000)
    components = models.CharField(default='one two three four five', max_length=100)
    price = models.DecimalField(decimal_places=2, max_digits=4)
    img = models.ImageField(upload_to='')
    
    def __str__(self):
        return self.name

orders/models.py
from django.db import models
from Category.models import Product


class Order(models.Model):
    name = models.CharField(max_length=60)
    table = models.CharField(max_length=150)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

pages/models.py
from django.db import models

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['name', 'table',]

Category/views.py
from django.shortcuts import render
from itertools import chain
from .models import Product


def menu_view(request, *args, **kwargs):
    category = request.GET.get('category', 'all')

    if category == 'drinks':
        obj = {'items': Product.objects.filter(category="Drink")}
    elif category == 'pizzas':
        obj = {'items': Product.objects.filter(category="Pizza")}
    elif category == 'desserts':
        obj = {'items': Product.objects.filter(category="Dessert")}
    elif category == 'burgers':
        obj = {'items': Product.objects.filter(category="Burger")}

    else:
        obj = {'items': Product.objects.all()}

    return render(request, "menu.html", obj)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from Category.models import Product
from .cart import Cart
from .forms import CartAddProductForm
import pdb

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id) 
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'detail.html', {'cart': cart})

orders/views.py
from django.shortcuts import render
from .models import OrderItem, Order
from .forms import OrderCreateForm
from cart.cart import Cart


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item['product'],
                    price=item['price'],
                    quantity=item['quantity']
                )
            cart.clear()
        return render(request, 'checkout_done.html', {'cart': cart,'order': order})
    else:
        form = OrderCreateForm()
    return render(request, 'checkout.html', {'cart': cart,'form': form})


def all_orders(request):

    orders = []
    for order in Order.objects.all():
        item = {}
        item["id"] = order.id
        item["table"] = order.table
        item["created"] = order.created
        item["items"] = OrderItem.objects.filter(order = order)
        orders.append(item)


    return render(request, 'orders.html', {'orders': orders})

pages/views.py
from django.shortcuts import render

# Create your views here.


def homepage(request, *args, **kwargs):
    table_num = request.GET.get('table', '0')
    return render(request, "home.html", {'table': table_num})

templates/base.html
{% load static %}

<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'styles/navbar/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'styles/up_navbar/up_navbar.css' %}">
    <link rel="stylesheet" href="{% static 'styles/homepage/home-block.css'%}">
    <link rel="stylesheet" href="{% static 'styles/footer/footer.css' %}">
    <link rel="stylesheet" href="{% static 'styles/base/base.css' %}">
    <link rel="stylesheet" href="{% static 'styles/menu/menu.css' %}">

    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
</head>
<header>
    <div class="row align-items-end">
        <div class="col-2"></div>
    </div>
    <div class="row align-items-start">
        <div class="col-2"></div>
    </div>

    {% include 'up_navbar.html' %}
    {% include 'navbar.html' %}
</header>

<body>
    <div class="container" id="space_for_items">
{% block content %}
{% endblock %}
    </div>
</body>
<footer id="footer" class="footer fixed-bottom">

    {% include 'footer.html' %}
</footer>
</html>

templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Checkout
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
            <div class="col-md-8">
                <h4 class="page-header">Checkout</h4>
                <form action="." method="post">
                    {% csrf_token %}
                    {{ form.as_p }}<br>
                    <input type="submit" class="btn btn-primary" value="Submit order">
                </form>
            </div>
            <div class="col-md-4">
                <div class="page-header">
                    Your Order
                </div>
                <ul class="list-group">
                    {% for item in cart %}
                        <li class="list-group-item">
                        {{ item.quantity }}x {{ item.product.name }}
                        <span>UAH. {{ item.total_price }}</span>
                        </li>
                    {% endfor %}

                <li class="list-group-item active">Total Cost: UAH. {{ cart.get_total_price }}</li>
                </ul>

            </div>
        </div>
    </div>
{% endblock %} 

templates/checkout_done.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Thank you
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
            <div class="col-md-8 col-md-offset-2">
                <h3 class="page-header">Thank You For Shopping With Us
                </h3>
                <p>Your order has been successfully completed. Your order number is <strong>{{ order.id }}</strong>.</p>
            </div>
        </div>
    </div>
{% endblock %} 

templates/detail.html
{% load static %}
{% load staticfiles %}

    <link rel="stylesheet" href="./static/styles/cart_detail/detail.css">
    <script src="../js/detail.js"></script>
    <script src="./js/detail.js"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">

{% block title %}
{% endblock %}


{% block content %}
<div class="container-fluid" id="cart">



        <div class=" cart_navbar col-12">
            <div class="row">
                <a onclick="history.back(-1)" class="col-2 d-flex justify-content-start arrow">
                    <img src="static/styles/cart_detail/cart_detail_img/back_button_img.png" class=" back_button ">
                </a>
                <div class="col-8 cart_navbar_title d-flex justify-content-center">Quick Checkout</div>
                <a href="/" class="col-2 d-flex justify-content-end cross">
                    <img src="static/styles/cart_detail/cart_detail_img/close_button.png" class="close_button ">
                </a>
            </div>
        </div>

        <div class="col-12 cart_details d-flex justify-content-start">
            {% with totail_items=cart|length %}
            {% if cart|length > 0 %}
            <a href="{% url 'cart:cart_detail' %}">
                <div class="cart_details d-flex justify-content-center">{{totail_items }} item in the cart list{{ totail_item|pluralize }}, USD {{ cart.get_total_price }}</div>
            </a>
            {% else %}
            Your cart is empty.
            {% endif %}
            {% endwith %}
        </div>

        <div class="col space_for_cartitems">
            <div class="col-12">
                {% for item in cart %}
                {% with product=item.product %}


                <div class="container-fluid item ">
                    <div class="col-12">
                        <div class="row">


                            <div class="col-6 imt_cont item_img_cont" >
                                <a href="{{ product.get__absolute_url }}" class="" >
                                    <img src="{{ product.img.url }}" class="item_img">
                                </a>
                            </div>


                            <div class="col-6 ml-auto align-self-center item_details" >
                                <div >
                                    <div class="row">

                                        <div class="col-11 item_name center d-flex justify-content-center" style="margin-top: -3vw" > • {{ product.name }}</div>
                                        <a href="{% url 'cart:cart_remove' product.id %}" class="col-1 d-flex justify-content-end" style="margin-top: -5vw">
                                            <img src="static/styles/cart_detail/cart_detail_img/cross_button.png" style="height: 3vw;width: auto;">
                                        </a>
                                    </div>

                                    <div class="row d-flex justify-content-center">
                                        <div class="row quantity">
                                            <div class="number_quantity" style="margin-bottom: -3vw">
                                                 <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                                    {% csrf_token %}
                                                    {{ item.update_quantity_form.quantity }}
                                                    {{ item.update_quantity_form.update }}
                                                    <input type="submit" value="Save" class="btn btn-info save-button">
                                                 </form>
                                            </div>

                                        </div>
                                    </div>
                                    <div class="row d-flex justify-content-center">
                                        <div class="preparing_time_border d-flex justify-content-center">
                                            <div class="preparing_time">
                                                {{product.preparing_time}}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row d-flex justify-content-center">
                                        <div class="price">
                                            ${{product.price}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                {% endwith %}
                {% endfor %}

            </div>
            {% if cart|length > 0 %}
            <footer class="fixed-bottom d-flex justify-content-center" style="background-color: white"  >
                    <div id="1" class="col-11 d-flex justify-content-center " style="background-color: #5663FF;width: 91vw;border-radius: 4vw;margin-bottom: 3vw">
                        <a id="2" href="{% url "orders:order_create" %}" class="order_button " style="font-size: 6vw; color: white;font-family: 'Josefin Sans Regular';margin-top: 4vw;padding-bottom: 3vw" >
                            Order
                        </a>
                    </div>
            </footer>
            {% endif %}
        </div>




    </div>

</div>
{% endblock %}

templates/footer.html
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<div class="container foooter">
     <div id="line"></div>
    <div class="row ml-auto mr-auto align-self-center ">
        <div class="col-4 d-flex justify-content-center ml-auto align-self-end " id="homepage">
            <a href="/menu?category=every">
                <div id="homepage_img"></div>
            </a>
        </div>
        <div class="col-4 d-flex justify-content-center" id="cart">
             <a href="/cart" class="url">
                 <div id="cart_circle">
                    <div id="cart_img"></div>
                 </div>
             </a>
        </div>
        <div class="col-4 d-flex justify-content-center ml-auto align-self-end " id="search">
             <a href="#">
                <div id="search_img"></div>
            </a>
        </div>
    </div>
</div>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<script>window.location.replace("/menu/?category=all")</script>
<img src="static/images/burger-title.png" alt="burger item" class="block_main">
<img src = {{ image }}>

    <ul class="under_block">
        <li class="left"><h3>American cheese</h3>
            <p>$15 <span class="category-title">Burger</span></p>
        </li>
        <li class="plus">
            <a href="#">+</a>
        </li>
    </ul>

{% endblock %}

templates/menu.html
{% extends 'base.html' %}
{% load static %}
Table {{ table }}
{% block content %}

{% for item in items %}
<div class="container item">
    <div class="col-12">
            <div class="img justify-content-center">
                <img class="block_main" id="img" src = /media/{{ item.img }}  alt="img" >
            </div>
            <div class="row">
                <div class="col-9">
                    <div class="row">
                        <div class="name d-flex justify-content-right">{{ item.name }}</div>
                    </div>
                    <div class="row">
                        <div class="border" id="category_border">
                            <div class="item_title d-flex justify-content-center" id="item_category_title">{{ item.category }}</div>
                        </div>
                        <div class="border" id="preparing_time_border">
                            <div class="item_title d-flex justify-content-center" id="item_preparing_time_title">{{item.preparing_time}}</div>
                        </div>
                    </div>
                    <div class="components row d-flex justify-content-left">{{item.components}}</div>
                    <div class="price row d-flex justify-content-left">${{item.price}}</div>
                </div>
                <div class="col-3 ml-auto align-self-right">
                    <a href="#" class="url">
                        <div class="row d-flex justify-content-center">

                            <div class="plus_border d-flex justify-content-center">
                                <form action="{% url "cart:cart_add" item.id %}" method="post">
                                    {% csrf_token %}
                                    {{ cart_product_form }}
                                    <input type="hidden" id="quantity" name="quantity" value="1">
                                    <input type="image" src="/static/styles/menu/menu_img/plus_white.png" id="plus_img">
                                </form>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>

{% endfor %}

<div class="empty_bottom_space"></div>
{% endblock %}

templates/navbar.html
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">

    <div class="container" id="space_for_icons">
        <div class="row" id="test">
            <div class="col-3 ml-auto align-self-center" id="pizza">
                <div class="category_icon">
                    <a href="/menu?category=pizzas" class="url">
                        <div class="row d-flex justify-content-center">
                            <div class="gradient" id="pizza_gradient"></div>
                            <div class="image" id="pizza_img"></div>
                            <div class="title">Pizza</div>
                        </div>
                    </a>
                </div>
            </div>



            <div class="col-3 ml-auto align-self-center" id="burger">
                <div class="category_icon">
                    <a href="/menu?category=burgers" class="url">
                        <div class="row d-flex justify-content-center">
                            <div class="gradient" id="burger_gradient"></div>
                            <div class="image" id="burger_img"></div>
                            <div class="title">Burgers</div>
                        </div>
                    </a>
                </div>
            </div>

            <div class="col-3 ml-auto align-self-center" id="deserts">
                <div class="category_icon">
                    <a href="/menu?category=desserts" class="url">
                        <div class="row d-flex justify-content-center">
                            <div class="gradient" id="desert_gradient"></div>
                            <div class="image" id="desert_img"></div>
                            <div class="title">Deserts</div>
                        </div>
                    </a>
                </div>
            </div>

            <div class="col-3 ml-auto align-self-center" id="drinks">
                <div class="category_icon">
                    <a href="/menu?category=drinks" class="url">
                        <div class="row d-flex justify-content-center">
                            <div class="gradient" id="drink_gradient"></div>
                            <div class="image" id="drink_img"></div>
                            <div class="title">Drinks</div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>

templates/orders.html
{% load static %}
{% load staticfiles %}
<html lang="en">
{% block title %}
    <head>
    <link rel="stylesheet" href="{% static 'styles/orders/orders.css' %}">
    <title>Orders</title>
    </head>
    <body>
    <div class="components-title row d-flex justify-content-left">Orders:</div>
{% endblock %}

{% block content %}
            {% for order in orders %}
                <div class="container">
                <div class="jumbotron">
                <ul class="list-group">
                    <div class="number-title row d-flex justify-content-left"><strong>№ {{ order.id }}:</strong></div>
                        <div class="items">
                <div class="components row d-flex justify-content-left">
                    Table №: {{ order.table }}
                <ul class="list-group">
                    {% for item in order.items %}
                        <li class="list-group-item">
                        {{ item.quantity }}x {{ item.product.name }} ({{ item.product.category }})
                        </li>
                    {% endfor %}
                </ul>
                </div>
                </div>
                </ul>
                </div>
                </div>
                <br />
            {% endfor %}
{% endblock %}
</body>
</html>

templates/up_navbar.html
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<div class="container " id="up_navbar">
    <div class="row">
        <div class="col-6 align-items-start">
            <div id="category_img" class="align-self-center"></div>
            <div id="category_title">Category</div>
        </div>
        <div class="col-6 align-items-end" >
            <!--
            <a href="#">
                <div id="category_see_all_list">See all</div>
            </a>
            -->
        </div>
    </div>
</div>